Repository halo-sigs/plugin-moments, pull requests merged in 2023-07, with the labels that each got.

#29 docs: update usage documentation of readme file
  README.md
Labels: approved, kind/documentation, lgtm, release-note-none

#17 feat: add tags feature for moment.
  build.gradle
  console/package.json
  console/pnpm-lock.yaml
  console/src/components/FilterTag.vue
  console/src/components/MomentEdit.vue
  console/src/components/MomentPreview.vue
  console/src/components/TextEditor.vue
  console/src/extensions/posts/index.ts
  console/src/extensions/tags/TagsExtensionView.vue
  console/src/extensions/tags/index.ts
  console/src/styles/index.css
  console/src/types/index.ts
  console/src/views/MomentsList.vue
  src/main/java/run/halo/moments/Moment.java
  src/main/java/run/halo/moments/MomentConfiguration.java
  src/main/java/run/halo/moments/MomentEndpoint.java
  src/main/java/run/halo/moments/MomentQuery.java
  src/main/java/run/halo/moments/MomentRouter.java
  src/main/java/run/halo/moments/MomentSorter.java
  src/main/java/run/halo/moments/MomentsPlugin.java
  src/main/java/run/halo/moments/TagMomentIndexer.java
  src/main/java/run/halo/moments/finders/MomentFinder.java
  src/main/java/run/halo/moments/finders/impl/MomentFinderImpl.java
  src/main/java/run/halo/moments/service/MomentService.java
  src/main/java/run/halo/moments/service/impl/MomentServiceImpl.java
  src/main/java/run/halo/moments/util/MeterUtils.java
  src/main/java/run/halo/moments/util/RSS2.java
  src/main/java/run/halo/moments/vo/MomentTagVo.java
  src/test/java/run/halo/moments/TagMomentIndexerTest.java
Labels: kind/feature, approved, release-note, lgtm

#31 pref: add accepts attribute when selecting files
  console/src/components/MomentEdit.vue
  console/src/components/PreviewDetailModal.vue
Labels: approved, release-note, lgtm, kind/improvement

#28 feat: add shortcuts for publish moment
  console/src/components/MomentEdit.vue
  src/main/resources/console/main.js
Labels: kind/feature, approved, release-note, lgtm

#33 refactor: support pagination when list by tag for theme-side
  src/main/java/run/halo/moments/MomentRouter.java
Labels: approved, lgtm, release-note-none

#35 chore: add halo app store release step
  .github/workflows/build.yml
Labels: approved, lgtm, release-note-none, kind/improvement

#36 docs: supplement tag documentation
  README.md
Labels: approved, lgtm, release-note-none
