Repository halo-sigs/plugin-moments, pull requests merged in 2023-04, with the labels that each got.

#3 locking pnpm version
  build.gradle
Labels: kind/bug, lgtm, release-note-none

#2 feat: completed the initial version design for the moments feature.
  README.md
  build.gradle
  console/.env
  console/.eslintrc.cjs
  console/package.json
  console/pnpm-lock.yaml
  console/postcss.config.js
  console/src/components/EditorBubbleMenu.vue
  console/src/components/EditorLinkBubbleMenuItems.vue
  console/src/components/MediaCard.vue
  console/src/components/MomentEdit.vue
  console/src/components/MomentItem.vue
  console/src/components/MomentPreview.vue
  console/src/components/PreviewDetailModal.vue
  console/src/components/TextEditor.vue
  console/src/composables/use-content-cache.ts
  console/src/extensions/posts/PostsView.vue
  console/src/extensions/posts/index.ts
  console/src/index.ts
  console/src/styles/index.css
  console/src/styles/tailwind.css
  console/src/types/index.ts
  console/src/utils/api-client.ts
  console/src/utils/date.ts
  console/src/views/MomentsList.vue
  console/tailwind.config.js
  console/vite.config.ts
  gradle/wrapper/gradle-wrapper.properties
  lib/halo-2.0.0-SNAPSHOT-plain.jar
  src/main/java/run/halo/moments/Contributor.java
  src/main/java/run/halo/moments/CustomEndpointsBuilder.java
  src/main/java/run/halo/moments/ListedMoment.java
  src/main/java/run/halo/moments/ModelConst.java
  src/main/java/run/halo/moments/Moment.java
  src/main/java/run/halo/moments/MomentConfiguration.java
  src/main/java/run/halo/moments/MomentEndpoint.java
  src/main/java/run/halo/moments/MomentQuery.java
  src/main/java/run/halo/moments/MomentRouter.java
  src/main/java/run/halo/moments/MomentSorter.java
  src/main/java/run/halo/moments/MomentsPlugin.java
  src/main/java/run/halo/moments/Stats.java
  src/main/java/run/halo/moments/finders/MomentFinder.java
  src/main/java/run/halo/moments/finders/impl/MomentFinderImpl.java
  src/main/java/run/halo/moments/service/MomentService.java
  src/main/java/run/halo/moments/service/impl/MomentServiceImpl.java
  src/main/java/run/halo/moments/util/MeterUtils.java
  src/main/java/run/halo/moments/vo/ContributorVo.java
  src/main/java/run/halo/moments/vo/MomentVo.java
  src/main/resources/console/main.js
  src/main/resources/console/style.css
  src/main/resources/extensions/roleTemplate.yaml
  src/main/resources/extensions/settings.yaml
  src/main/resources/logo.svg
  src/main/resources/plugin.yaml
Labels: kind/feature, approved, release-note, lgtm

#8 fix: modify pagination criteria
  console/src/views/MomentsList.vue
  src/main/resources/console/main.js
  src/main/resources/console/style.css
Labels: kind/bug, approved, release-note, lgtm

#10 feat: support iframe and lazy-load display of media resources.
  console/src/components/MomentPreview.vue
  console/src/components/TextEditor.vue
Labels: kind/feature, approved, release-note, lgtm

#9 fix: resolve the issue of unable to delete pictures.
  console/src/components/MomentEdit.vue
  src/main/resources/console/main.js
Labels: kind/bug, approved, release-note, lgtm

#11 perf: improve styles
  console/.eslintrc.cjs
  console/src/components/MediaCard.vue
  console/src/components/MomentEdit.vue
  console/src/components/MomentItem.vue
  console/src/components/MomentPreview.vue
  console/src/styles/tailwind.css
  console/src/views/MomentsList.vue
  console/tailwind.config.js
  src/main/resources/console/main.js
  src/main/resources/console/style.css
Labels: approved, release-note, lgtm, kind/improvement
