Repository halo-sigs/plugin-moments, pull requests merged in 2024-06, with the labels that each got.

#109 chore: add app-id annotation
  src/main/resources/plugin.yaml
Labels: approved, lgtm, release-note-none

#106 refactor: adapt subscription for notifications based on expressions
  build.gradle
  src/main/java/run/halo/moments/CommentNotificationReasonPublisher.java
  src/main/java/run/halo/moments/MomentReconciler.java
  src/main/java/run/halo/moments/MomentsPlugin.java
  src/main/java/run/halo/moments/SchemeRegistered.java
  src/main/java/run/halo/moments/SubscriptionMigration.java
  src/main/resources/plugin.yaml
Labels: approved, release-note, lgtm

#111 chore: update plugin.yaml
  src/main/resources/plugin.yaml
Labels: approved, lgtm, release-note-none

#112 fix: layout issues on low-resolution screens
  console/src/uc/MomentsList.vue
  console/src/views/MomentsList.vue
  console/tailwind.config.js
Labels: kind/bug, lgtm, release-note-none
