Repository halo-sigs/plugin-moments, pull requests merged in 2024-07, with the labels that each got.

#114 refactor: use globally provided axios instance
  build.gradle
  console/package.json
  console/pnpm-lock.yaml
  console/src/components/MomentEdit.vue
  console/src/components/MomentItem.vue
  console/src/composables/use-tag.ts
  console/src/uc/MomentEdit.vue
  console/src/uc/MomentItem.vue
  console/src/uc/MomentsList.vue
  console/src/utils/api-client.ts
  console/src/views/MomentsList.vue
  console/vite.config.ts
  src/main/resources/plugin.yaml
Labels: approved, release-note, lgtm, kind/improvement

#118 refactor: integrate unocss and improve UI
  console/.eslintrc.cjs
  console/package.json
  console/pnpm-lock.yaml
  console/postcss.config.js
  console/src/components/EditorBubbleMenu.vue
  console/src/components/EditorLinkBubbleMenuItems.vue
  console/src/components/FilterDropdown.vue
  console/src/components/MediaCard.vue
  console/src/components/MomentEdit.vue
  console/src/components/MomentItem.vue
  console/src/components/MomentPreview.vue
  console/src/components/PreviewDetailModal.vue
  console/src/components/TagFilterDropdown.vue
  console/src/components/TextEditor.vue
  console/src/extensions/images/index.ts
  console/src/extensions/tags/TagsExtensionView.vue
  console/src/index.ts
  console/src/styles/index.scss
  console/src/styles/tailwind.css
  console/src/uc/MomentEdit.vue
  console/src/uc/MomentItem.vue
  console/src/uc/MomentsList.vue
  console/src/uc/TagFilterDropdown.vue
  console/src/views/MomentsList.vue
  console/tailwind.config.js
  console/uno.config.ts
  console/vite.config.ts
Labels: approved, lgtm, release-note-none

#119 chore: rewrite springdoc with parameter
  src/main/java/run/halo/moments/MomentEndpoint.java
  src/main/java/run/halo/moments/MomentQuery.java
  src/main/java/run/halo/moments/uc/UcMomentEndpoint.java
Labels: approved, lgtm, release-note-none, kind/improvement

#120 chore: update Node.js and pnpm versions
  .github/workflows/cd.yaml
  .github/workflows/ci.yaml
Labels: approved, lgtm, release-note-none
