Repository halo-sigs/plugin-moments, pull requests merged in 2024-05, with the labels that each got.

#96 chore: update workflows config
  .github/workflows/build.yml
  .github/workflows/cd.yaml
  .github/workflows/ci.yaml
  build.gradle
Labels: approved, lgtm, release-note-none

#75 fix: solve the problem of the tag input becoming a title after the # symbol
  console/src/components/TextEditor.vue
Labels: kind/bug, release-note, lgtm

#98 fix: unable to stop normally when the startup fails
  src/main/java/run/halo/moments/MomentsPlugin.java
Labels: kind/bug, approved, release-note

#100 feat: the editor supports command to add pictures
  console/src/components/TextEditor.vue
  console/src/extensions/images/index.ts
Labels: kind/feature, release-note

#99 fix: the picture is cropped when previewing
  console/src/components/PreviewDetailModal.vue
Labels: kind/bug, release-note

#101 feat: add the function of jumping to the front desk
  console/src/views/MomentsList.vue
Labels: approved, lgtm

#103 docs: update readme
  README.md
  images/plugin-moments-preview.png
Labels: approved, kind/documentation, lgtm, release-note-none
