Repository halo-sigs/plugin-moments, pull requests merged in 2024-02, with the labels that each got.

#69 refactor: using indexes to optimize queries
  build.gradle
  src/main/java/run/halo/moments/Moment.java
  src/main/java/run/halo/moments/MomentConfiguration.java
  src/main/java/run/halo/moments/MomentEndpoint.java
  src/main/java/run/halo/moments/MomentQuery.java
  src/main/java/run/halo/moments/MomentReconciler.java
  src/main/java/run/halo/moments/MomentRouter.java
  src/main/java/run/halo/moments/MomentSorter.java
  src/main/java/run/halo/moments/MomentsPlugin.java
  src/main/java/run/halo/moments/TagMomentIndexer.java
  src/main/java/run/halo/moments/finders/impl/MomentFinderImpl.java
  src/main/java/run/halo/moments/service/MomentService.java
  src/main/java/run/halo/moments/service/impl/MomentServiceImpl.java
  src/main/resources/plugin.yaml
  src/test/java/run/halo/moments/TagMomentIndexerTest.java
Labels: approved, release-note, lgtm

#73 fix: solve the route exception problem of tag
  console/src/components/MomentPreview.vue
  console/src/views/MomentsList.vue
Labels: kind/bug, approved, release-note, lgtm

#79 refactor: refactor the ui of moments interface and remove the search feature
  console/package.json
  console/pnpm-lock.yaml
  console/src/components/FilterTag.vue
  console/src/components/MomentEdit.vue
  console/src/components/MomentItem.vue
  console/src/components/MomentPreview.vue
  console/src/components/TagFilterDropdown.vue
  console/src/styles/index.scss
  console/src/utils/date.ts
  console/src/views/MomentsList.vue
Labels: release-note, lgtm, kind/improvement

#81 fix: access the list interface without logging in
  console/src/components/MomentEdit.vue
  console/src/extensions/tags/TagsExtensionView.vue
  console/src/views/MomentsList.vue
  src/main/java/run/halo/moments/MomentEndpoint.java
  src/main/resources/extensions/roleTemplate.yaml
Labels: kind/bug, approved, release-note, lgtm, kind/api-change

#80 feat: add an API for moment detail
  src/main/java/run/halo/moments/ListedMoment.java
  src/main/java/run/halo/moments/MomentEndpoint.java
  src/main/java/run/halo/moments/exception/NotFoundException.java
  src/main/java/run/halo/moments/service/MomentService.java
  src/main/java/run/halo/moments/service/impl/MomentServiceImpl.java
Labels: kind/feature, approved, release-note, lgtm, kind/api-change

#82 fix: resolve the issue of API error for not found tags
  console/src/components/TagFilterDropdown.vue
Labels: kind/bug, approved, lgtm, release-note-none

#84 fix: tag filter list not refresh
  console/src/components/TagFilterDropdown.vue
Labels: kind/bug, approved, lgtm, release-note-none

#83 pref: optimize the ui in moment editing mode
  console/src/components/MomentItem.vue
  console/src/components/MomentPreview.vue
  console/src/views/MomentsList.vue
Labels: approved, release-note, lgtm, kind/improvement
